# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-latest'
  workspace:
    clean: all
variables:
  scheme: 'rnfirstapp'
  sdk: 'iphoneos'
  configuration: 'Release'
  variables:
    - group: React Native Variables

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      gem cleanup
      gem install xcpretty
      gem install --no-document bundler
      bundle update --bundler
      bundle install --retry=3 --jobs=4
      gem install fastlane

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: npm install
    workingDirectory: '$(Build.Repository.LocalPath)'

# CocoaPods
# Install CocoaPods dependencies for Swift and Objective-C Cocoa projects
- task: Bash@3
  inputs:
    targetType: 'inline'
    script:  |
     pod deintegrate
     gem install cocoapods
     pod install
     pod --version
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    forceRepoUpdate: true
    #projectDirectory: # Optional
- task: InstallAppleCertificate@2
  inputs:
     certSecureFile: AppleCertification_12June.p12
     certPwd: $(P12password)
     keychain: 'temp'
     deleteCert: true
  displayName: Install Apple Certificate

- task: InstallAppleProvisioningProfile@1
  inputs:
     provisioningProfileLocation: 'secureFiles'
     provProfileSecureFile: 'certification_ios_poc.developerprofile'
  displayName: 'Install Apple Provisioning Profile'

- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    actions: 'clean archive'
    archivePath: 'rnfirstapp.xcarchive'
    xcWorkspacePath: '**/*.xcworkspace'
    configuration: '$(configuration)'
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    teamId: $(TEAMID)
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    exportOptionsPlist: '$(Build.Repository.LocalPath)/ios/ExportOptions.plist'
    exportTeamId: $(TEAMID)
    useXcpretty: true
    packageApp: true

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop