# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
# - task: Xcode@5
#   inputs:
#     sdk: '$(sdk)'
#     scheme: '$(scheme)'
#     configuration: '$(configuration)'
#     xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
#     packageApp: false

- script: nvm install v15.5.1
  displayName: 'update node to 15.5.1'

- script: npm i
  displayName: 'install dependencies'

- script: /usr/local/bin/pod install
  displayName: 'pod install using a script'
  
- task: CocoaPods@0
  displayName: 'pod install using the CocoaPods task with defaults'
  
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true
    projectDirectory: '$(system.defaultWorkingDirectory)'
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'

- script: npm run ios
  displayName: 'build rn ios app'