# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: 'rnfirstapp'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'install'
 
# CocoaPods
# Install CocoaPods dependencies for Swift and Objective-C Cocoa projects
- task: CocoaPods@0
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    forceRepoUpdate: true
    #projectDirectory: # Optional
- task: DownloadSecureFile@1
  name: caCertificate
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'Certificates_ios.p12'

- script: |
    echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...
    sudo chown root:root $(caCertificate.secureFilePath)
    sudo chmod a+r $(caCertificate.secureFilePath)
    sudo ln -s -t /etc/ssl/certs/ $(caCertificate.secureFilePath)
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    actions: 'clean archive'
    archivePath: 'rnfirstapp.xcarchive'
    xcWorkspacePath: '**/*.xcworkspace'
    configuration: '$(configuration)'
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
    teamId: $(TEAMID)
    provisioningProfileUuid: $(PROFILEID)
    provisioningProfileName: $(PROFILENAME)
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: true

# - task: CmdLine@2
#   inputs:
#     workingDirectory: '$(Build.Repository.LocalPath)/ios'
#     script: pod install

# - task: CmdLine@2
#   inputs:
#     workingDirectory: '$(Build.Repository.LocalPath)/ios'
#     script: xcodebuild clean archive -workspace rnfirstapp.xcworkspace -scheme "rnfirstapp" -archivePath rnfirstapp.xcarchive