resources:
  repositories:
  - repository: demo-serenity-appium
    type: github
    endpoint: LayMui
    name: LayMui/demo-serenity-appium
    trigger: applitools
    
trigger:
- master

stages:
  -   stage: Build_Test
      displayName: Build and Test artifacts
      jobs:
        -   job: Build_Test
            pool:
              vmImage: 'macOS-latest'

            steps:
            - checkout: self
            - task: NodeTool@0
              inputs:
                versionSpec: '10.x'
              displayName: 'Install Node.js'
              
            - task: UseRubyVersion@0
              inputs:
                versionSpec: '>= 2.4'
                
            - script: |
                gem install xcpretty
              workingDirectory: $(Build.SourcesDirectory)/react-native-app-demo
              displayName: 'gem install xcpretty'

            - script: |
                npm install
              workingDirectory: $(Build.SourcesDirectory)/react-native-app-demo
              displayName: 'npm install'
            
            - script: |
                pod install
                xcodebuild clean archive -workspace rnfirstapp.xcworkspace -scheme "rnfirstapp" -archivePath rnfirstapp.xcarchive
                xcodebuild -exportArchive -archivePath rnfirstapp.xcarchive -exportPath rnfirstapp -exportOptionsPlist ExportOptions.plist | xcpretty
              workingDirectory: $(Build.SourcesDirectory)/react-native-app-demo/ios
              displayName: 'pod install and xcodebuild to build ipa artefact'


            - task: CopyFiles@2
              inputs:
                sourceFolder: $(Build.SourcesDirectory)/react-native-app-demo
                contents: |
                  **
                TargetFolder: $(Build.ArtifactStagingDirectory)
            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: $(Build.ArtifactStagingDirectory)
                artifactName: app-source-folder
            - script: |
                rm -r $(Build.ArtifactStagingDirectory)

            - checkout: demo-serenity-appium
            - script: |
                  ./serenity.sh iOS_realdevice 
                  workingDirectory: $(Build.SourcesDirectory)/demo-serenity-appium
                  displayName: 'run serenity appium test'

 