# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/xcode
pool:
  vmImage: 'macOS-10.14'
variables:
  scheme: 'rnfirstapp'
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
   # exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false

- task: CmdLine@2
  inputs:
    workingDirectory: '$(Build.Repository.LocalPath)/ios'
    script: pod install